/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as TradeGoldIndexRouteImport } from './trade-gold/index'
import { Route as QrIndexRouteImport } from './qr/index'
import { Route as EventIndexRouteImport } from './event/index'
import { Route as BlogsIndexRouteImport } from './blogs/index'
import { Route as ApiGoldPriceRouteImport } from './api/gold-price'
import { Route as BlogsReviewYear2025IndexRouteImport } from './blogs/review-year-2025/index'
import { Route as BlogsItkmitlReview2026IndexRouteImport } from './blogs/itkmitl-review-2026/index'
import { Route as ApiSpotifyNowPlayingRouteImport } from './api/spotify/now-playing'
import { Route as ApiSpotifyLyricsRouteImport } from './api/spotify/lyrics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeGoldIndexRoute = TradeGoldIndexRouteImport.update({
  id: '/trade-gold/',
  path: '/trade-gold/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrIndexRoute = QrIndexRouteImport.update({
  id: '/qr/',
  path: '/qr/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIndexRoute = EventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoldPriceRoute = ApiGoldPriceRouteImport.update({
  id: '/api/gold-price',
  path: '/api/gold-price',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsReviewYear2025IndexRoute =
  BlogsReviewYear2025IndexRouteImport.update({
    id: '/blogs/review-year-2025/',
    path: '/blogs/review-year-2025/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsItkmitlReview2026IndexRoute =
  BlogsItkmitlReview2026IndexRouteImport.update({
    id: '/blogs/itkmitl-review-2026/',
    path: '/blogs/itkmitl-review-2026/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSpotifyNowPlayingRoute = ApiSpotifyNowPlayingRouteImport.update({
  id: '/api/spotify/now-playing',
  path: '/api/spotify/now-playing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyLyricsRoute = ApiSpotifyLyricsRouteImport.update({
  id: '/api/spotify/lyrics',
  path: '/api/spotify/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/gold-price': typeof ApiGoldPriceRoute
  '/blogs/': typeof BlogsIndexRoute
  '/event/': typeof EventIndexRoute
  '/qr/': typeof QrIndexRoute
  '/trade-gold/': typeof TradeGoldIndexRoute
  '/api/spotify/lyrics': typeof ApiSpotifyLyricsRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
  '/blogs/itkmitl-review-2026/': typeof BlogsItkmitlReview2026IndexRoute
  '/blogs/review-year-2025/': typeof BlogsReviewYear2025IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/gold-price': typeof ApiGoldPriceRoute
  '/blogs': typeof BlogsIndexRoute
  '/event': typeof EventIndexRoute
  '/qr': typeof QrIndexRoute
  '/trade-gold': typeof TradeGoldIndexRoute
  '/api/spotify/lyrics': typeof ApiSpotifyLyricsRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
  '/blogs/itkmitl-review-2026': typeof BlogsItkmitlReview2026IndexRoute
  '/blogs/review-year-2025': typeof BlogsReviewYear2025IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/gold-price': typeof ApiGoldPriceRoute
  '/blogs/': typeof BlogsIndexRoute
  '/event/': typeof EventIndexRoute
  '/qr/': typeof QrIndexRoute
  '/trade-gold/': typeof TradeGoldIndexRoute
  '/api/spotify/lyrics': typeof ApiSpotifyLyricsRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
  '/blogs/itkmitl-review-2026/': typeof BlogsItkmitlReview2026IndexRoute
  '/blogs/review-year-2025/': typeof BlogsReviewYear2025IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/gold-price'
    | '/blogs/'
    | '/event/'
    | '/qr/'
    | '/trade-gold/'
    | '/api/spotify/lyrics'
    | '/api/spotify/now-playing'
    | '/blogs/itkmitl-review-2026/'
    | '/blogs/review-year-2025/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/gold-price'
    | '/blogs'
    | '/event'
    | '/qr'
    | '/trade-gold'
    | '/api/spotify/lyrics'
    | '/api/spotify/now-playing'
    | '/blogs/itkmitl-review-2026'
    | '/blogs/review-year-2025'
  id:
    | '__root__'
    | '/'
    | '/api/gold-price'
    | '/blogs/'
    | '/event/'
    | '/qr/'
    | '/trade-gold/'
    | '/api/spotify/lyrics'
    | '/api/spotify/now-playing'
    | '/blogs/itkmitl-review-2026/'
    | '/blogs/review-year-2025/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGoldPriceRoute: typeof ApiGoldPriceRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  EventIndexRoute: typeof EventIndexRoute
  QrIndexRoute: typeof QrIndexRoute
  TradeGoldIndexRoute: typeof TradeGoldIndexRoute
  ApiSpotifyLyricsRoute: typeof ApiSpotifyLyricsRoute
  ApiSpotifyNowPlayingRoute: typeof ApiSpotifyNowPlayingRoute
  BlogsItkmitlReview2026IndexRoute: typeof BlogsItkmitlReview2026IndexRoute
  BlogsReviewYear2025IndexRoute: typeof BlogsReviewYear2025IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-gold/': {
      id: '/trade-gold/'
      path: '/trade-gold'
      fullPath: '/trade-gold/'
      preLoaderRoute: typeof TradeGoldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/': {
      id: '/qr/'
      path: '/qr'
      fullPath: '/qr/'
      preLoaderRoute: typeof QrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/': {
      id: '/event/'
      path: '/event'
      fullPath: '/event/'
      preLoaderRoute: typeof EventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gold-price': {
      id: '/api/gold-price'
      path: '/api/gold-price'
      fullPath: '/api/gold-price'
      preLoaderRoute: typeof ApiGoldPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/review-year-2025/': {
      id: '/blogs/review-year-2025/'
      path: '/blogs/review-year-2025'
      fullPath: '/blogs/review-year-2025/'
      preLoaderRoute: typeof BlogsReviewYear2025IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/itkmitl-review-2026/': {
      id: '/blogs/itkmitl-review-2026/'
      path: '/blogs/itkmitl-review-2026'
      fullPath: '/blogs/itkmitl-review-2026/'
      preLoaderRoute: typeof BlogsItkmitlReview2026IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/now-playing': {
      id: '/api/spotify/now-playing'
      path: '/api/spotify/now-playing'
      fullPath: '/api/spotify/now-playing'
      preLoaderRoute: typeof ApiSpotifyNowPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/lyrics': {
      id: '/api/spotify/lyrics'
      path: '/api/spotify/lyrics'
      fullPath: '/api/spotify/lyrics'
      preLoaderRoute: typeof ApiSpotifyLyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGoldPriceRoute: ApiGoldPriceRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  EventIndexRoute: EventIndexRoute,
  QrIndexRoute: QrIndexRoute,
  TradeGoldIndexRoute: TradeGoldIndexRoute,
  ApiSpotifyLyricsRoute: ApiSpotifyLyricsRoute,
  ApiSpotifyNowPlayingRoute: ApiSpotifyNowPlayingRoute,
  BlogsItkmitlReview2026IndexRoute: BlogsItkmitlReview2026IndexRoute,
  BlogsReviewYear2025IndexRoute: BlogsReviewYear2025IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
