/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as TradeGoldIndexRouteImport } from './trade-gold/index'
import { Route as EventIndexRouteImport } from './event/index'
import { Route as BlogsIndexRouteImport } from './blogs/index'
import { Route as BlogsReviewYear2025IndexRouteImport } from './blogs/review-year-2025/index'
import { Route as BlogsItkmitlReview2026IndexRouteImport } from './blogs/itkmitl-review-2026/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeGoldIndexRoute = TradeGoldIndexRouteImport.update({
  id: '/trade-gold/',
  path: '/trade-gold/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIndexRoute = EventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsReviewYear2025IndexRoute =
  BlogsReviewYear2025IndexRouteImport.update({
    id: '/blogs/review-year-2025/',
    path: '/blogs/review-year-2025/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsItkmitlReview2026IndexRoute =
  BlogsItkmitlReview2026IndexRouteImport.update({
    id: '/blogs/itkmitl-review-2026/',
    path: '/blogs/itkmitl-review-2026/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/event/': typeof EventIndexRoute
  '/trade-gold/': typeof TradeGoldIndexRoute
  '/blogs/itkmitl-review-2026/': typeof BlogsItkmitlReview2026IndexRoute
  '/blogs/review-year-2025/': typeof BlogsReviewYear2025IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/event': typeof EventIndexRoute
  '/trade-gold': typeof TradeGoldIndexRoute
  '/blogs/itkmitl-review-2026': typeof BlogsItkmitlReview2026IndexRoute
  '/blogs/review-year-2025': typeof BlogsReviewYear2025IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/event/': typeof EventIndexRoute
  '/trade-gold/': typeof TradeGoldIndexRoute
  '/blogs/itkmitl-review-2026/': typeof BlogsItkmitlReview2026IndexRoute
  '/blogs/review-year-2025/': typeof BlogsReviewYear2025IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs/'
    | '/event/'
    | '/trade-gold/'
    | '/blogs/itkmitl-review-2026/'
    | '/blogs/review-year-2025/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blogs'
    | '/event'
    | '/trade-gold'
    | '/blogs/itkmitl-review-2026'
    | '/blogs/review-year-2025'
  id:
    | '__root__'
    | '/'
    | '/blogs/'
    | '/event/'
    | '/trade-gold/'
    | '/blogs/itkmitl-review-2026/'
    | '/blogs/review-year-2025/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  EventIndexRoute: typeof EventIndexRoute
  TradeGoldIndexRoute: typeof TradeGoldIndexRoute
  BlogsItkmitlReview2026IndexRoute: typeof BlogsItkmitlReview2026IndexRoute
  BlogsReviewYear2025IndexRoute: typeof BlogsReviewYear2025IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-gold/': {
      id: '/trade-gold/'
      path: '/trade-gold'
      fullPath: '/trade-gold/'
      preLoaderRoute: typeof TradeGoldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/': {
      id: '/event/'
      path: '/event'
      fullPath: '/event/'
      preLoaderRoute: typeof EventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/review-year-2025/': {
      id: '/blogs/review-year-2025/'
      path: '/blogs/review-year-2025'
      fullPath: '/blogs/review-year-2025/'
      preLoaderRoute: typeof BlogsReviewYear2025IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/itkmitl-review-2026/': {
      id: '/blogs/itkmitl-review-2026/'
      path: '/blogs/itkmitl-review-2026'
      fullPath: '/blogs/itkmitl-review-2026/'
      preLoaderRoute: typeof BlogsItkmitlReview2026IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  EventIndexRoute: EventIndexRoute,
  TradeGoldIndexRoute: TradeGoldIndexRoute,
  BlogsItkmitlReview2026IndexRoute: BlogsItkmitlReview2026IndexRoute,
  BlogsReviewYear2025IndexRoute: BlogsReviewYear2025IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
