/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as UrldecoderIndexRouteImport } from './urldecoder/index'
import { Route as ToolsIndexRouteImport } from './tools/index'
import { Route as QrIndexRouteImport } from './qr/index'
import { Route as McIndexRouteImport } from './mc/index'
import { Route as EventIndexRouteImport } from './event/index'
import { Route as ColorIndexRouteImport } from './color/index'
import { Route as BlogsIndexRouteImport } from './blogs/index'
import { Route as ArchiveIndexRouteImport } from './archive/index'
import { Route as ApiMcPingRouteImport } from './api/mc-ping'
import { Route as ApiGoldPriceRouteImport } from './api/gold-price'
import { Route as FormsTaroFocusPointIndexRouteImport } from './forms/taro-focus-point/index'
import { Route as BlogsReviewYear2025IndexRouteImport } from './blogs/review-year-2025/index'
import { Route as BlogsItkmitlReview2026IndexRouteImport } from './blogs/itkmitl-review-2026/index'
import { Route as ApiSpotifyNowPlayingRouteImport } from './api/spotify/now-playing'
import { Route as ApiSpotifyLyricsRouteImport } from './api/spotify/lyrics'
import { Route as ApiFormsTaroFocusPointRouteImport } from './api/forms/taro-focus-point'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrldecoderIndexRoute = UrldecoderIndexRouteImport.update({
  id: '/urldecoder/',
  path: '/urldecoder/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrIndexRoute = QrIndexRouteImport.update({
  id: '/qr/',
  path: '/qr/',
  getParentRoute: () => rootRouteImport,
} as any)
const McIndexRoute = McIndexRouteImport.update({
  id: '/mc/',
  path: '/mc/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIndexRoute = EventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorIndexRoute = ColorIndexRouteImport.update({
  id: '/color/',
  path: '/color/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcPingRoute = ApiMcPingRouteImport.update({
  id: '/api/mc-ping',
  path: '/api/mc-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoldPriceRoute = ApiGoldPriceRouteImport.update({
  id: '/api/gold-price',
  path: '/api/gold-price',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsTaroFocusPointIndexRoute =
  FormsTaroFocusPointIndexRouteImport.update({
    id: '/forms/taro-focus-point/',
    path: '/forms/taro-focus-point/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsReviewYear2025IndexRoute =
  BlogsReviewYear2025IndexRouteImport.update({
    id: '/blogs/review-year-2025/',
    path: '/blogs/review-year-2025/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsItkmitlReview2026IndexRoute =
  BlogsItkmitlReview2026IndexRouteImport.update({
    id: '/blogs/itkmitl-review-2026/',
    path: '/blogs/itkmitl-review-2026/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSpotifyNowPlayingRoute = ApiSpotifyNowPlayingRouteImport.update({
  id: '/api/spotify/now-playing',
  path: '/api/spotify/now-playing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyLyricsRoute = ApiSpotifyLyricsRouteImport.update({
  id: '/api/spotify/lyrics',
  path: '/api/spotify/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsTaroFocusPointRoute = ApiFormsTaroFocusPointRouteImport.update({
  id: '/api/forms/taro-focus-point',
  path: '/api/forms/taro-focus-point',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/gold-price': typeof ApiGoldPriceRoute
  '/api/mc-ping': typeof ApiMcPingRoute
  '/archive/': typeof ArchiveIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/color/': typeof ColorIndexRoute
  '/event/': typeof EventIndexRoute
  '/mc/': typeof McIndexRoute
  '/qr/': typeof QrIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/urldecoder/': typeof UrldecoderIndexRoute
  '/api/forms/taro-focus-point': typeof ApiFormsTaroFocusPointRoute
  '/api/spotify/lyrics': typeof ApiSpotifyLyricsRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
  '/blogs/itkmitl-review-2026/': typeof BlogsItkmitlReview2026IndexRoute
  '/blogs/review-year-2025/': typeof BlogsReviewYear2025IndexRoute
  '/forms/taro-focus-point/': typeof FormsTaroFocusPointIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/gold-price': typeof ApiGoldPriceRoute
  '/api/mc-ping': typeof ApiMcPingRoute
  '/archive': typeof ArchiveIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/color': typeof ColorIndexRoute
  '/event': typeof EventIndexRoute
  '/mc': typeof McIndexRoute
  '/qr': typeof QrIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/urldecoder': typeof UrldecoderIndexRoute
  '/api/forms/taro-focus-point': typeof ApiFormsTaroFocusPointRoute
  '/api/spotify/lyrics': typeof ApiSpotifyLyricsRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
  '/blogs/itkmitl-review-2026': typeof BlogsItkmitlReview2026IndexRoute
  '/blogs/review-year-2025': typeof BlogsReviewYear2025IndexRoute
  '/forms/taro-focus-point': typeof FormsTaroFocusPointIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/gold-price': typeof ApiGoldPriceRoute
  '/api/mc-ping': typeof ApiMcPingRoute
  '/archive/': typeof ArchiveIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/color/': typeof ColorIndexRoute
  '/event/': typeof EventIndexRoute
  '/mc/': typeof McIndexRoute
  '/qr/': typeof QrIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/urldecoder/': typeof UrldecoderIndexRoute
  '/api/forms/taro-focus-point': typeof ApiFormsTaroFocusPointRoute
  '/api/spotify/lyrics': typeof ApiSpotifyLyricsRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
  '/blogs/itkmitl-review-2026/': typeof BlogsItkmitlReview2026IndexRoute
  '/blogs/review-year-2025/': typeof BlogsReviewYear2025IndexRoute
  '/forms/taro-focus-point/': typeof FormsTaroFocusPointIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/gold-price'
    | '/api/mc-ping'
    | '/archive/'
    | '/blogs/'
    | '/color/'
    | '/event/'
    | '/mc/'
    | '/qr/'
    | '/tools/'
    | '/urldecoder/'
    | '/api/forms/taro-focus-point'
    | '/api/spotify/lyrics'
    | '/api/spotify/now-playing'
    | '/blogs/itkmitl-review-2026/'
    | '/blogs/review-year-2025/'
    | '/forms/taro-focus-point/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/gold-price'
    | '/api/mc-ping'
    | '/archive'
    | '/blogs'
    | '/color'
    | '/event'
    | '/mc'
    | '/qr'
    | '/tools'
    | '/urldecoder'
    | '/api/forms/taro-focus-point'
    | '/api/spotify/lyrics'
    | '/api/spotify/now-playing'
    | '/blogs/itkmitl-review-2026'
    | '/blogs/review-year-2025'
    | '/forms/taro-focus-point'
  id:
    | '__root__'
    | '/'
    | '/api/gold-price'
    | '/api/mc-ping'
    | '/archive/'
    | '/blogs/'
    | '/color/'
    | '/event/'
    | '/mc/'
    | '/qr/'
    | '/tools/'
    | '/urldecoder/'
    | '/api/forms/taro-focus-point'
    | '/api/spotify/lyrics'
    | '/api/spotify/now-playing'
    | '/blogs/itkmitl-review-2026/'
    | '/blogs/review-year-2025/'
    | '/forms/taro-focus-point/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGoldPriceRoute: typeof ApiGoldPriceRoute
  ApiMcPingRoute: typeof ApiMcPingRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ColorIndexRoute: typeof ColorIndexRoute
  EventIndexRoute: typeof EventIndexRoute
  McIndexRoute: typeof McIndexRoute
  QrIndexRoute: typeof QrIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  UrldecoderIndexRoute: typeof UrldecoderIndexRoute
  ApiFormsTaroFocusPointRoute: typeof ApiFormsTaroFocusPointRoute
  ApiSpotifyLyricsRoute: typeof ApiSpotifyLyricsRoute
  ApiSpotifyNowPlayingRoute: typeof ApiSpotifyNowPlayingRoute
  BlogsItkmitlReview2026IndexRoute: typeof BlogsItkmitlReview2026IndexRoute
  BlogsReviewYear2025IndexRoute: typeof BlogsReviewYear2025IndexRoute
  FormsTaroFocusPointIndexRoute: typeof FormsTaroFocusPointIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urldecoder/': {
      id: '/urldecoder/'
      path: '/urldecoder'
      fullPath: '/urldecoder/'
      preLoaderRoute: typeof UrldecoderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/': {
      id: '/qr/'
      path: '/qr'
      fullPath: '/qr/'
      preLoaderRoute: typeof QrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mc/': {
      id: '/mc/'
      path: '/mc'
      fullPath: '/mc/'
      preLoaderRoute: typeof McIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/': {
      id: '/event/'
      path: '/event'
      fullPath: '/event/'
      preLoaderRoute: typeof EventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color/': {
      id: '/color/'
      path: '/color'
      fullPath: '/color/'
      preLoaderRoute: typeof ColorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mc-ping': {
      id: '/api/mc-ping'
      path: '/api/mc-ping'
      fullPath: '/api/mc-ping'
      preLoaderRoute: typeof ApiMcPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gold-price': {
      id: '/api/gold-price'
      path: '/api/gold-price'
      fullPath: '/api/gold-price'
      preLoaderRoute: typeof ApiGoldPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/taro-focus-point/': {
      id: '/forms/taro-focus-point/'
      path: '/forms/taro-focus-point'
      fullPath: '/forms/taro-focus-point/'
      preLoaderRoute: typeof FormsTaroFocusPointIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/review-year-2025/': {
      id: '/blogs/review-year-2025/'
      path: '/blogs/review-year-2025'
      fullPath: '/blogs/review-year-2025/'
      preLoaderRoute: typeof BlogsReviewYear2025IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/itkmitl-review-2026/': {
      id: '/blogs/itkmitl-review-2026/'
      path: '/blogs/itkmitl-review-2026'
      fullPath: '/blogs/itkmitl-review-2026/'
      preLoaderRoute: typeof BlogsItkmitlReview2026IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/now-playing': {
      id: '/api/spotify/now-playing'
      path: '/api/spotify/now-playing'
      fullPath: '/api/spotify/now-playing'
      preLoaderRoute: typeof ApiSpotifyNowPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/lyrics': {
      id: '/api/spotify/lyrics'
      path: '/api/spotify/lyrics'
      fullPath: '/api/spotify/lyrics'
      preLoaderRoute: typeof ApiSpotifyLyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/taro-focus-point': {
      id: '/api/forms/taro-focus-point'
      path: '/api/forms/taro-focus-point'
      fullPath: '/api/forms/taro-focus-point'
      preLoaderRoute: typeof ApiFormsTaroFocusPointRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGoldPriceRoute: ApiGoldPriceRoute,
  ApiMcPingRoute: ApiMcPingRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ColorIndexRoute: ColorIndexRoute,
  EventIndexRoute: EventIndexRoute,
  McIndexRoute: McIndexRoute,
  QrIndexRoute: QrIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  UrldecoderIndexRoute: UrldecoderIndexRoute,
  ApiFormsTaroFocusPointRoute: ApiFormsTaroFocusPointRoute,
  ApiSpotifyLyricsRoute: ApiSpotifyLyricsRoute,
  ApiSpotifyNowPlayingRoute: ApiSpotifyNowPlayingRoute,
  BlogsItkmitlReview2026IndexRoute: BlogsItkmitlReview2026IndexRoute,
  BlogsReviewYear2025IndexRoute: BlogsReviewYear2025IndexRoute,
  FormsTaroFocusPointIndexRoute: FormsTaroFocusPointIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
